export default function attributes({
  id = null,
  numberCheckIn = 0,
  month = null,
  year = null,
  userIds = [null],
  user = {
    role: {
      absoluteDeveloper: false,
      developer: false,
      director: false,
      executive: false,
      admin: false,
      user: true,
    },
    accessLevel: 50,
    plan: null,
    disabled: false,
    displayName: null,
    name: { firstName: null, lastName: null },
    address: {
      line1: null,
      line2: null,
      postcode: null,
      state: null,
      country: null,
    },
    dateOfBirth: null,
    gender: null,
    username: null,
    email: null,
    emailVerified: false,
    identityNumber: null,
    phoneNumber: null,
    notificationToken: [],
    photoURL: null,
    providerId: null,
    lastLoginAt: null,
    created: { at: null, by: null },
    deleted: { at: null, by: null },
    updated: { at: null, by: null },
    id: null,
  },
  voucherIds = [null],
  voucher = {
    id: null,
    active: false,
    assigned: false,
    claimed: false,
    amount: 0,
    quantity: 1,
    title: null,
    description: null,
    tnc: null,
    usedDate: { at: null, by: null },
    checkInIds: [null],
    merchantIds: [null],
    merchant: {
      id: null,
      businessName: null,
      businessRegistrationNumber: null,
      email: null,
      phoneNumber: null,
      address: { 
        line1: null,
        line2: null,
        postcode: null,
        state: null,
        country: null
      },
      shops: [null],
      superadmin: [null],
      admins: [null],
      categories: [null],
      dateJoined: new Date,
      created: { at: null, by: null },
      deleted: { at: null, by: null },
    },
    shopIds: [null],
    shop: {
      id: null,
      title: null,
      displayTitle: null,
      subtitle: null,
      description: null,
      logo: [null],
      images: [null],
      facebookUrl: null,
      instagramUrl: null,
      websiteUrl: null,
      whatsapp: null,
      phoneNumber: null,
      email: null,
      address: {
        line1: null,
        line2: null,
        postcode: null,
        state: null,
        country: null,
      },
      operatingHour: [{ day: null, open: null, close: null, operate: false }],
      merchants: [null],
      manager: [null],
      supervisor: [null],
      worker: [null],
      tags: [null],
      categories: [null],
      isPromote: false,
      dateJoined: new Date(),
      created: { at: null, by: null },
      deleted: { at: null, by: null },
      updated: { at: null, by: null },
      l: objectDataServices.GeoPoint(0, 0),
      g: null,
    },
    prevUserIds: [{id: null, prevAssignedDate: null}],
    assignedDate: { at: null, by: null },
    expiryDate: null,
    startDate: new Date(),
    endDate: new Date(),
    created: { at: null, by: null },
    deleted: { at: null, by: null },
    updated: { at: null, by: null },
  },
  created = { at: null, by: null },
  deleted = { at: null, by: null },
  updated = { at: null, by: null },
}) {
  const packaging = {
    id,
    userIds,
    user,
    voucherIds,
    voucher,
    numberCheckIn,
    month,
    year,
    created,
    deleted,
    updated,
  };

  const shared = {
    ...packaging,
  };

  const confidential = {
    ...shared,
  };

  const receivableState = {
    id,
    userIds,
  };

 /*  const manualUpdatableState = {
    confidential: {
      ["checkIns"]: checkIns,
    },
  }; */

  return {
    packaging,
    shared,
    confidential,
    receivableState,
    //manualUpdatableState,
  };
}
