import { dataServices as objectDataServices } from "../../../marslab-library-cloud-function/services/database";

export default function attributes({
  id = null,
  active = false,
  assigned = false,
  claimed = false,
  amount = 0,
  quantity = 1,
  title = null,
  description = null,
  tnc = null,
  usedDate = { at: null, by: null },
  checkInIds=[null],
  merchantIds=[null],
  merchant = {
    id: null,
    businessName: null,
    businessRegistrationNumber: null,
    email: null,
    phoneNumber: null,
    address: { 
      line1: null,
      line2: null,
      postcode: null,
      state: null,
      country: null
    },
    shops: [null],
    superadmin: [null],
    admins: [null],
    categories: [null],
    dateJoined: new Date,
    created: { at: null, by: null },
    deleted: { at: null, by: null },
  },
  shopIds = [null],
  shop = {
    id: null,
    title: null,
    displayTitle: null,
    subtitle: null,
    description: null,
    logo: [null],
    images: [null],
    facebookUrl: null,
    instagramUrl: null,
    websiteUrl: null,
    whatsapp: null,
    phoneNumber: null,
    email: null,
    address: {
      line1: null,
      line2: null,
      postcode: null,
      state: null,
      country: null,
    },
    operatingHour: [{ day: null, open: null, close: null, operate: false }],
    merchants: [null],
    manager: [null],
    supervisor: [null],
    worker: [null],
    tags: [null],
    categories: [null],
    isPromote: false,
    dateJoined: new Date(),
    created: { at: null, by: null },
    deleted: { at: null, by: null },
    updated: { at: null, by: null },
    l: objectDataServices.GeoPoint(0, 0),
    g: null,
  },
  userIds = [null],
  user = {
    role: {
      absoluteDeveloper: false,
      developer: false,
      director: false,
      executive: false,
      admin: false,
      user: true,
    },
    accessLevel: 50,
    plan: null,
    disabled: false,
    displayName: null,
    name: { firstName: null, lastName: null },
    address: {
      line1: null,
      line2: null,
      postcode: null,
      state: null,
      country: null,
    },
    dateOfBirth: null,
    gender: null,
    username: null,
    email: null,
    emailVerified: false,
    identityNumber: null,
    phoneNumber: null,
    notificationToken: [],
    photoURL: null,
    providerId: null,
    lastLoginAt: null,
    created: { at: null, by: null },
    deleted: { at: null, by: null },
    updated: { at: null, by: null },
    id: null,
  },
  prevUserIds = [{id: null, prevAssignedDate: null}],
  assignedDate = { at: null, by: null },
  expiryDate = null,
  startDate = new Date(),
  endDate = new Date(),
  created = { at: null, by: null },
  deleted = { at: null, by: null },
  updated = { at: null, by: null },
}) {
  const packaging = {
    id,
    active,
    assigned,
    claimed,
    amount,
    usedDate,
    title,
    description,
    tnc,
    checkInIds,
    userIds,
    user,
    prevUserIds,
    merchantIds,
    merchant,
    shopIds,
    shop,
    assignedDate,
    expiryDate,
    startDate,
    endDate,
    created,
    deleted,
    updated,
  };

  const shared = {
    ...packaging,
  };

  const confidential = {
    ...shared,
  };

  const receivableState = {
    id,
    active,
    assigned,
    claimed,
    amount,
    usedDate,
    title,
    description,
    tnc,
    userIds,
    checkInIds,
    prevUserIds,
    merchantIds,
    shopIds,
    assignedDate,
    expiryDate,
    startDate,
    endDate,
    quantity
    //prevAssignedDate,
  };

  const manualUpdatableState = {
    confidential: {
      ["amount"]: amount,
      ["description"]: description,
      ["tnc"]: tnc,
      ["title"]: title,
      ["merchantIds"]: merchantIds,
      ["startDate"]: startDate,
      ["endDate"]: endDate,
    },
  };

  const assignObjectState = {
    confidential: {
      userIds,
      user,
      claimed,
      assigned,
      assignedDate,
      expiryDate,
    },
  };

  const claimObjectState = {
    confidential: {
      usedDate,
    },
  };
  return {
    packaging,
    shared,
    confidential,
    receivableState,
    manualUpdatableState,
    assignObjectState,
    claimObjectState,
  };
}
